### ISSUE TITLE
Application throws an exception when partner joins

### ISSUE THREAD

**Issue by richwestcoast** [ZacharyTalis/alyx-multiplayer#3]
![image](https://user-images.githubusercontent.com/23324896/130309516-a29c627d-89b6-4dbf-a3b4-eeda4e613e71.png)

IndexOutOfRangeException

Anyone know how I can resolve this issue?

**Comment by ZacharyTalis** [comment]
Oop, thanks for the heads-up!

I don't know where to begin with *reproducing* your issue, but there's a few clues that something's fricked.

[This method](https://github.com/ZacharyTalis/alyx-multiplayer/blob/7b4fa77eb843202f2d1b12b6ac9d164facbfd4101/MemoryWatcher.cs#L21) we pulled from the LiveSplit code is where the error actually occurs. But before that, alyx-multiplayer identifies your Alyx map name as `0x7FF...`, when it should be giving you a plaintext map name. Also, the localHead index # is printed twice!

A few questions:

> Are you accidentially running two or more instances of HL:A or alyx-multiplayer on the same machine?
> Are you running alyx-multiplayer as administrator? (you should be)
> What debugging steps have you attempted so far? Restarting your computers, checking the Alyx console log, etc etc
> What does the alyx-multiplayer output look like *before* the exception occurs?

If you can, try to get that map name to display correctly before having the other player connect.

**Comment by richwestcoast** [comment]
> 
> 
> Oop, thanks for the heads-up!
> 
> I don't know where to begin with _reproducing_ your issue, but there's a few clues that something's fricked.
> 
> [This method](https://github.com/ZacharyTalis/alyx-multiplayer/blob/7b4fa77eb843202f2d1b12b6ac9d164facbfd4101/MemoryWatcher.cs#L21) we pulled from the LiveSplit code is where the error actually occurs. But before that, alyx-multiplayer identifies your Alyx map name as `0x7FF...`, when it should be giving you a plaintext map name. Also, the localHead index # is printed twice!
> 
> A few questions:
> 
> > Are you accidentially running two or more instances of HL:A or alyx-multiplayer on the same machine?
> > Are you running alyx-multiplayer as administrator? (you should be)
> > What debugging steps have you attempted so far? Restarting your computers, checking the Alyx console log, etc etc
> > What does the alyx-multiplayer output look like _before_ the exception occurs?
> 
> If you can, try to get that map name to display correctly before having the other player connect.

Are you accidentially running two or more instances of HL:A or alyx-multiplayer on the same machine?
Nope only one copy

Are you running alyx-multiplayer as administrator? (you should be)
Yes

What debugging steps have you attempted so far? Restarting your computers, checking the Alyx console log, etc etc
Restarted the host PC & partner PC, opened closed alyx multiple times on both devices, restarted the Alyx-multiplayer multiple times (again on both devices), tried over VPN (hense why I left the IP addresses visable, not a internet IP)

What does the alyx-multiplayer output look like _before_ the exception occurs?
What you see in the screenshot

**Comment by richwestcoast** [comment]
I have tried again launching the alyx-multiplayer app and the map name will not appear in plaintext.

**Comment by ZacharyTalis** [comment]
Would you be down to debug this issue with me over Discord voice call sometime? I'm **Kube # four five five six**, if ya wanna shoot me a message.

Assuming we figure it out, I'll update this Issue with our solution.

**Comment by richwestcoast** [comment]
Sure I will send you an invite :)

**Comment by richwestcoast** [comment]
After successfully debugging the issue, we came away with a few useful commands to help trouble shoot issues.

Firstly make sure to enable the console within Half-Life Alyx, do so by right clicking Half-Life: Alyx (within Steam) > Properties > enter "-console -vconsole" to Launch Options text field. & Apply/Close.

Then once console has been enabled proceed to launch the game.

Once Half-Life Alyx is running press the tilde key to bring up the console.

First check the mod is configured correctly by typing `"addon_list"` within HL Alyx console
Output should be the following: 
![photo_2021-09-14_23-57-54](https://user-images.githubusercontent.com/135821/133339542-4e71e4f5-4c8e-4d38-8e86-3495faf2e94d.jpg)

Once you have confirmed the mod is configured correctly, start a game by issuing the following command in the console: `addon_play a1_intro_world`

Within the console you should see your location reference & your partners location ref.
![photo_2021-09-14_23-58-00](https://user-images.githubusercontent.com/135821/133339942-1885d836-6d8c-4cda-9838-e63c60362bd0.jpg)

*Another gotcha is if you click within the console you might pause the plugin, pressing enter can resovle this issue @ZacharyTalis perhaps you can elaborate on this nuance?*
